In [62]:
"Step 1: load packages"
library(tidyverse)
library(lubridate)
library(dplyr)
library(ggplot2)
library(tidyr)

[1] "Step 1: load packages"

In [63]:
"Step 2 : load and prepare Data"
activity<-read.csv("/kaggle/input/fitbit/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv")
calories <-read.csv("/kaggle/input/fitbit/Fitabase Data 4.12.16-5.12.16/dailyCalories_merged.csv")
sleep<-read.csv("/kaggle/input/fitbit/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv")
heartrate <-read.csv("/kaggle/input/fitbit/Fitabase Data 4.12.16-5.12.16/heartrate_seconds_merged.csv")
weight<-read.csv("/kaggle/input/fitbit/Fitabase Data 4.12.16-5.12.16/weightLogInfo_merged.csv")

[1] "Step 2 : load and prepare Data"

**Step 3.1 : Check data integrity**

In [64]:
"Quick Summary"

head(activity)
str(activity)

head(calories)
str(calories)

head(sleep)
str(sleep)

head(heartrate)
str(heartrate)

head(weight)
str(weight)

[1] "Quick Summary"

  Id         ActivityDate TotalSteps TotalDistance TrackerDistance
1 1503960366 4/12/2016    13162      8.50          8.50
2 1503960366 4/13/2016    10735      6.97          6.97
3 1503960366 4/14/2016    10460      6.74          6.74
4 1503960366 4/15/2016     9762      6.28          6.28
5 1503960366 4/16/2016    12669      8.16          8.16
6 1503960366 4/17/2016     9705      6.48          6.48
  LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
1 0                        1.88               0.55
2 0                        1.57               0.69
3 0                        2.44               0.40
4 0                        2.14               1.26
5 0                        2.71               0.41
6 0                        3.19               0.78
  LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
1 6.06                0                       25
2 4.71                0                       21
3 3.91                0                       30
4 2.83                0                       29
5 5.04                0                       36
6 2.51                0                       38
  FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
1 13                  328                   728             1985
2 19                  217                   776             1797
3 11                  181                  1218             1776
4 34                  209                   726             1745
5 10                  221                   773             1863
6 20                  164                   539             1728

'data.frame':	940 obs. of  15 variables:
 $ Id                      : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityDate            : chr  "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
 $ TotalSteps              : int  13162 10735 10460 9762 12669 9705 13019 15506 10544 9819 ...
 $ TotalDistance           : num  8.5 6.97 6.74 6.28 8.16 ...
 $ TrackerDistance         : num  8.5 6.97 6.74 6.28 8.16 ...
 $ LoggedActivitiesDistance: num  0 0 0 0 0 0 0 0 0 0 ...
 $ VeryActiveDistance      : num  1.88 1.57 2.44 2.14 2.71 ...
 $ ModeratelyActiveDistance: num  0.55 0.69 0.4 1.26 0.41 ...
 $ LightActiveDistance     : num  6.06 4.71 3.91 2.83 5.04 ...
 $ SedentaryActiveDistance : num  0 0 0 0 0 0 0 0 0 0 ...
 $ VeryActiveMinutes       : int  25 21 30 29 36 38 42 50 28 19 ...
 $ FairlyActiveMinutes     : int  13 19 11 34 10 20 16 31 12 8 ...
 $ LightlyActiveMinutes    : int  328 217 181 209 221 164 233 264 205 211 ...
 $ SedentaryMinutes        : int  728 776 1218 726 773 539 1149 775 818 838 ...
 $ Calories                : int  1985 1797 1776 1745 1863 1728 1921 2035 1786 1775 ...

  Id         ActivityDay Calories
1 1503960366 4/12/2016   1985
2 1503960366 4/13/2016   1797
3 1503960366 4/14/2016   1776
4 1503960366 4/15/2016   1745
5 1503960366 4/16/2016   1863
6 1503960366 4/17/2016   1728

'data.frame':	940 obs. of  3 variables:
 $ Id         : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityDay: chr  "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
 $ Calories   : int  1985 1797 1776 1745 1863 1728 1921 2035 1786 1775 ...

  Id         SleepDay              TotalSleepRecords TotalMinutesAsleep
1 1503960366 4/12/2016 12:00:00 AM 1                 327
2 1503960366 4/13/2016 12:00:00 AM 2                 384
3 1503960366 4/15/2016 12:00:00 AM 1                 412
4 1503960366 4/16/2016 12:00:00 AM 2                 340
5 1503960366 4/17/2016 12:00:00 AM 1                 700
6 1503960366 4/19/2016 12:00:00 AM 1                 304
  TotalTimeInBed
1 346
2 407
3 442
4 367
5 712
6 320

'data.frame':	413 obs. of  5 variables:
 $ Id                : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ SleepDay          : chr  "4/12/2016 12:00:00 AM" "4/13/2016 12:00:00 AM" "4/15/2016 12:00:00 AM" "4/16/2016 12:00:00 AM" ...
 $ TotalSleepRecords : int  1 2 1 2 1 1 1 1 1 1 ...
 $ TotalMinutesAsleep: int  327 384 412 340 700 304 360 325 361 430 ...
 $ TotalTimeInBed    : int  346 407 442 367 712 320 377 364 384 449 ...

  Id         Time                 Value
1 2022484408 4/12/2016 7:21:00 AM  97
2 2022484408 4/12/2016 7:21:05 AM 102
3 2022484408 4/12/2016 7:21:10 AM 105
4 2022484408 4/12/2016 7:21:20 AM 103
5 2022484408 4/12/2016 7:21:25 AM 101
6 2022484408 4/12/2016 7:22:05 AM  95

'data.frame':	2483658 obs. of  3 variables:
 $ Id   : num  2.02e+09 2.02e+09 2.02e+09 2.02e+09 2.02e+09 ...
 $ Time : chr  "4/12/2016 7:21:00 AM" "4/12/2016 7:21:05 AM" "4/12/2016 7:21:10 AM" "4/12/2016 7:21:20 AM" ...
 $ Value: int  97 102 105 103 101 95 91 93 94 93 ...

  Id         Date                  WeightKg WeightPounds Fat BMI
1 1503960366 5/2/2016 11:59:59 PM   52.6    115.9631     22  22.65
2 1503960366 5/3/2016 11:59:59 PM   52.6    115.9631     NA  22.65
3 1927972279 4/13/2016 1:08:52 AM  133.5    294.3171     NA  47.54
4 2873212765 4/21/2016 11:59:59 PM  56.7    125.0021     NA  21.45
5 2873212765 5/12/2016 11:59:59 PM  57.3    126.3249     NA  21.69
6 4319703577 4/17/2016 11:59:59 PM  72.4    159.6147     25  27.45
  IsManualReport LogId
1 True           1.462234e+12
2 True           1.462320e+12
3 False          1.460510e+12
4 True           1.461283e+12
5 True           1.463098e+12
6 True           1.460938e+12

'data.frame':	67 obs. of  8 variables:
 $ Id            : num  1.50e+09 1.50e+09 1.93e+09 2.87e+09 2.87e+09 ...
 $ Date          : chr  "5/2/2016 11:59:59 PM" "5/3/2016 11:59:59 PM" "4/13/2016 1:08:52 AM" "4/21/2016 11:59:59 PM" ...
 $ WeightKg      : num  52.6 52.6 133.5 56.7 57.3 ...
 $ WeightPounds  : num  116 116 294 125 126 ...
 $ Fat           : int  22 NA NA NA NA 25 NA NA NA NA ...
 $ BMI           : num  22.6 22.6 47.5 21.5 21.7 ...
 $ IsManualReport: chr  "True" "True" "False" "True" ...
 $ LogId         : num  1.46e+12 1.46e+12 1.46e+12 1.46e+12 1.46e+12 ...

In [65]:
"Checking unquide users"

n_distinct(activity$Id)
n_distinct(calories$Id)
n_distinct(sleep$Id)
n_distinct(weight$Id)
n_distinct(heartrate$Id)


"The tabeles have difrent number of unquide users. There are 30 partisipans but activity and calories have 33 diffrent id numbers. Weight has only 8"

[1] "Checking unquide users"

[1] 33

[1] 33

[1] 24

[1] 8

[1] 14

[1] "The tabeles have difrent number of unquide users. There are 30 partisipans but activity and calories have 33 diffrent id numbers. Weight has only 8"

In [66]:
"Cheking for dublicates"

"activity" 
sum(duplicated(activity))
"calories"
sum(duplicated(calories))
"sleep"
sum(duplicated(sleep))
"weight"
sum(duplicated(weight))
"heartrate"
sum(duplicated(heartrate))

"The table sleep has 3 dublicates"

[1] "Cheking for dublicates"

[1] "activity"

[1] 0

[1] "calories"

[1] 0

[1] "sleep"

[1] 3

[1] "weight"

[1] 0

[1] "heartrate"

[1] 0

[1] "The table sleep has 3 dublicates"

In [67]:
"Checking for missing values"
"activity"
sum(is.na(activity))
"calories"
sum(is.na(calories))
"sleep"
sum(is.na(sleep))
"weight"
sum(is.na(weight))
"heartrate"
sum(is.na(heartrate))

"The table weight has 65 missing values"

[1] "Checking for missing values"

[1] "activity"

[1] 0

[1] "calories"

[1] 0

[1] "sleep"

[1] 0

[1] "weight"

[1] 65

[1] "heartrate"

[1] 0

[1] "The table weight has 65 missing values"

**3.2 Cleaning Process**

In [68]:
"deleting dublicates"
sleep <- sleep[!duplicated(sleep),]

[1] "deleting dublicates"

In [69]:
"quick Check"

sum(duplicated(sleep))

[1] "quick Check"

[1] 0

In [70]:
"Converting into time and date format"
activity <- activity %>%
    rename(date = ActivityDate) %>%
    mutate(date = as_date(date, format = "%m/%d/%Y"))
sleep <- sleep %>%
  rename(date = SleepDay) %>%
  mutate(date = as_date(date,format ="%m/%d/%Y %I:%M:%S %p" , tz=Sys.timezone()))

[1] "Converting into time and date format"

Warning message:
“`tz` argument is ignored by `as_date()`”

In [72]:
"Quick Check"

head(sleep)
head(activity)

[1] "Quick Check"

  Id         date       TotalSleepRecords TotalMinutesAsleep TotalTimeInBed
1 1503960366 2016-04-12 1                 327                346
2 1503960366 2016-04-13 2                 384                407
3 1503960366 2016-04-15 1                 412                442
4 1503960366 2016-04-16 2                 340                367
5 1503960366 2016-04-17 1                 700                712
6 1503960366 2016-04-19 1                 304                320

  Id         date       TotalSteps TotalDistance TrackerDistance
1 1503960366 2016-04-12 13162      8.50          8.50
2 1503960366 2016-04-13 10735      6.97          6.97
3 1503960366 2016-04-14 10460      6.74          6.74
4 1503960366 2016-04-15  9762      6.28          6.28
5 1503960366 2016-04-16 12669      8.16          8.16
6 1503960366 2016-04-17  9705      6.48          6.48
  LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
1 0                        1.88               0.55
2 0                        1.57               0.69
3 0                        2.44               0.40
4 0                        2.14               1.26
5 0                        2.71               0.41
6 0                        3.19               0.78
  LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
1 6.06                0                       25
2 4.71                0                       21
3 3.91                0                       30
4 2.83                0                       29
5 5.04                0                       36
6 2.51                0                       38
  FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
1 13                  328                   728             1985
2 19                  217                   776             1797
3 11                  181                  1218             1776
4 34                  209                   726             1745
5 10                  221                   773             1863
6 20                  164                   539             1728

**3.3 Transformation Process**

In [75]:
"Merging activity and sleep" 
activity_sleep <- merge(activity,sleep, by = c ("Id", "date"))

head(activity_sleep)

[1] "Merging activity and sleep"

  Id         date       TotalSteps TotalDistance TrackerDistance
1 1503960366 2016-04-12 13162      8.50          8.50
2 1503960366 2016-04-13 10735      6.97          6.97
3 1503960366 2016-04-15  9762      6.28          6.28
4 1503960366 2016-04-16 12669      8.16          8.16
5 1503960366 2016-04-17  9705      6.48          6.48
6 1503960366 2016-04-19 15506      9.88          9.88
  LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
1 0                        1.88               0.55
2 0                        1.57               0.69
3 0                        2.14               1.26
4 0                        2.71               0.41
5 0                        3.19               0.78
6 0                        3.53               1.32
  LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
1 6.06                0                       25
2 4.71                0                       21
3 2.83                0                       29
4 5.04                0                       36
5 2.51                0                       38
6 5.03                0                       50
  FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
1 13                  328                  728              1985
2 19                  217                  776              1797
3 34                  209                  726              1745
4 10                  221                  773              1863
5 20                  164                  539              1728
6 31                  264                  775              2035
  TotalSleepRecords TotalMinutesAsleep TotalTimeInBed
1 1                 327                346
2 2                 384                407
3 1                 412                442
4 2                 340                367
5 1                 700                712
6 1                 304                320

**Step 4 : Analysis**

In [76]:
summary(activity_sleep)

       Id                 date              TotalSteps    TotalDistance
 Min.   :1.504e+09   Min.   :2016-04-12   Min.   :   17   Min.   : 0.010
 1st Qu.:3.977e+09   1st Qu.:2016-04-19   1st Qu.: 5189   1st Qu.: 3.592
 Median :4.703e+09   Median :2016-04-27   Median : 8913   Median : 6.270
 Mean   :4.995e+09   Mean   :2016-04-26   Mean   : 8515   Mean   : 6.012
 3rd Qu.:6.962e+09   3rd Qu.:2016-05-04   3rd Qu.:11370   3rd Qu.: 8.005
 Max.   :8.792e+09   Max.   :2016-05-12   Max.   :22770   Max.   :17.540
 TrackerDistance  LoggedActivitiesDistance VeryActiveDistance
 Min.   : 0.010   Min.   :0.0000           Min.   : 0.000
 1st Qu.: 3.592   1st Qu.:0.0000           1st Qu.: 0.000
 Median : 6.270   Median :0.0000           Median : 0.570
 Mean   : 6.007   Mean   :0.1089           Mean   : 1.446
 3rd Qu.: 7.950   3rd Qu.:0.0000           3rd Qu.: 2.360
 Max.   :17.540   Max.   :4.0817           Max.   :12.540
 ModeratelyActiveDistance LightActiveDistance SedentaryActiveDistance
 Min.   :0.0000           Min.   :0.010       Min.   :0.0000000
 1st Qu.:0.0000           1st Qu.:2.540       1st Qu.:0.0000000
 Median :0.4200           Median :3.665       Median :0.0000000
 Mean   :0.7439           Mean   :3.791       Mean   :0.0009268
 3rd Qu.:1.0375           3rd Qu.:4.918       3rd Qu.:0.0000000
 Max.   :6.4800           Max.   :9.480       Max.   :0.1100000
 VeryActiveMinutes FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes
 Min.   :  0.00    Min.   :  0.00      Min.   :  2.0        Min.   :   0.0
 1st Qu.:  0.00    1st Qu.:  0.00      1st Qu.:158.0        1st Qu.: 631.2
 Median :  9.00    Median : 11.00      Median :208.0        Median : 717.0
 Mean   : 25.05    Mean   : 17.92      Mean   :216.5        Mean   : 712.1
 3rd Qu.: 38.00    3rd Qu.: 26.75      3rd Qu.:263.0        3rd Qu.: 782.8
 Max.   :210.00    Max.   :143.00      Max.   :518.0        Max.   :1265.0
    Calories    TotalSleepRecords TotalMinutesAsleep TotalTimeInBed
 Min.   : 257   Min.   :1.00      Min.   : 58.0      Min.   : 61.0
 1st Qu.:1841   1st Qu.:1.00      1st Qu.:361.0      1st Qu.:403.8
 Median :2207   Median :1.00      Median :432.5      Median :463.0
 Mean   :2389   Mean   :1.12      Mean   :419.2      Mean   :458.5
 3rd Qu.:2920   3rd Qu.:1.00      3rd Qu.:490.0      3rd Qu.:526.0
 Max.   :4900   Max.   :3.00      Max.   :796.0      Max.   :961.0

In [78]:
summary(calories)

       Id            ActivityDay           Calories
 Min.   :1.504e+09   Length:940         Min.   :   0
 1st Qu.:2.320e+09   Class :character   1st Qu.:1828
 Median :4.445e+09   Mode  :character   Median :2134
 Mean   :4.855e+09                      Mean   :2304
 3rd Qu.:6.962e+09                      3rd Qu.:2793
 Max.   :8.878e+09                      Max.   :4900

In [79]:
summary(weight)

       Id                Date              WeightKg       WeightPounds
 Min.   :1.504e+09   Length:67          Min.   : 52.60   Min.   :116.0
 1st Qu.:6.962e+09   Class :character   1st Qu.: 61.40   1st Qu.:135.4
 Median :6.962e+09   Mode  :character   Median : 62.50   Median :137.8
 Mean   :7.009e+09                      Mean   : 72.04   Mean   :158.8
 3rd Qu.:8.878e+09                      3rd Qu.: 85.05   3rd Qu.:187.5
 Max.   :8.878e+09                      Max.   :133.50   Max.   :294.3

      Fat             BMI        IsManualReport         LogId
 Min.   :22.00   Min.   :21.45   Length:67          Min.   :1.460e+12
 1st Qu.:22.75   1st Qu.:23.96   Class :character   1st Qu.:1.461e+12
 Median :23.50   Median :24.39   Mode  :character   Median :1.462e+12
 Mean   :23.50   Mean   :25.19                      Mean   :1.462e+12
 3rd Qu.:24.25   3rd Qu.:25.56                      3rd Qu.:1.462e+12
 Max.   :25.00   Max.   :47.54                      Max.   :1.463e+12
 NA's   :65

In [80]:
summary(heartrate)

       Id                Time               Value
 Min.   :2.022e+09   Length:2483658     Min.   : 36.00
 1st Qu.:4.388e+09   Class :character   1st Qu.: 63.00
 Median :5.554e+09   Mode  :character   Median : 73.00
 Mean   :5.514e+09                      Mean   : 77.33
 3rd Qu.:6.962e+09                      3rd Qu.: 88.00
 Max.   :8.878e+09                      Max.   :203.00

"Step 4.1 Daily usage"